language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk7
    - os: linux
      jdk: openjdk7
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode7

cache:
  directories:
    - $HOME/.m2

after_success:
  - mvn clean test jacoco:report coveralls:report