package:
 name: jovial 
 version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}

source:
 git_url: ../../

build:
 number: 0
 noarch: generic

requirements:
 build:
  - openjdk 8.*
 run:
  - openjdk 8.*

